### ISSUE TITLE
Question about license

### ISSUE THREAD

**Issue by Domosed-gamin** [jcsims/zzzzzzzzzzzz#1]
This is soooooooooo cute game. I love ASCII games. Thank you for shared code. Please tell me which license you use for it?

**Comment by Domosed-gamin** [comment]
Best game ever. I finished it. Please add more hardcore levels. :-)
https://imgur.com/a/0cKnmW9

**Comment by jcsims** [comment]
Added! I'm glad you enjoyed it. We had a ton of fun making it, and I'm having fun playing it again!
